version: "3.8"

services:
  devcontainer:
    build:
      dockerfile: Dockerfile
      context: .

    command: /bin/sh -c "while sleep 1000; do :; done"

    volumes:
      - ..:/workspace/SubscriptionForm:cached

    network_mode: service:db

    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped

    ports:
      - "1433:1433"

    volumes:
      - mssqlvolume_subscriptionform:/var/opt/mssql

    env_file:
      - ../.env.development

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express

volumes:
  mssqlvolume_subscriptionform:
    external: true
    name: mssqlvolume_subscriptionform
